spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      uri: http://localhost:8888
      #      uri: http://platform-config:8888
      enabled: true
  profiles:
    active: dev