# Configuración general del micro servicio que contiene el nombre del servicio, puerto local, contexto y archivo de log
server:
    port: ${PORT:0}
#  port: 8081
logging:
  file:
    name: msa-administracion.log
  level.org.springframework.security: DEBUG
  level.org.springframework.security.oauth2: DEBUG
  level.org.springframework.web: DEBUG

# Configuración del micro servicio
spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://famisoftdb.postgres.database.azure.com:5432/msa-famisoft-prueba
    username: usrdbown@famisoftdb
    password: fjb$%lc98Fuoiew%p
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      pool-name: msa-administracion
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

# Resolución del servidor de Eureka
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/platform-eureka/eureka
